apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.7.0
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
          volumeMounts:
            - mountPath: /etc/loki
              name: config-volume
            - mountPath: /loki
              name: loki-data
      volumes:
        - name: config-volume
          configMap:
            name: loki-config
        - name: loki-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: observability
spec:
  ports:
    - port: 3100
      targetPort: 3100
  selector:
    app: loki
