apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: observability
data:
  loki-config.yaml: |
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
    ingester:
      chunk_target_size: 1048576
      max_chunks_per_stream: 2000
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
      filesystem:
        directory: /loki/chunks
    limits_config:
      max_streams_per_user: 1000
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb_shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h
