apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: apiserver
        scheme: https
        tls_config:
          insecure_skip_verify: true
        relabel_configs:
          - source_labels: [__meta_kubernetes_apiserver_scheme]
            target_label: __scheme__
          - source_labels: [__meta_kubernetes_apiserver_name]
            target_label: __param_target
          - target_label: instance
            replacement: kubernetes

      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
    # Add more scrape_configs for scraping Kubernetes metrics and pods
